export default {
  "conditionSelector": {
    "and": "conditionSelector.and",
    "or": "conditionSelector.or",
    "not": "conditionSelector.not",
    "true": "conditionSelector.true",
    "false": "conditionSelector.false",
    "add_front": "conditionSelector.add_front",
    "add_medium": "conditionSelector.add_medium",
    "delete_this": "conditionSelector.delete_this",
    "constant": "conditionSelector.constant",
    "variable": "conditionSelector.variable",
    "compare": "conditionSelector.compare",
  },
  "if": {
    "if": "if.if",
    "then": "if.then",
    "else": "if.else",
    "add_else": "if.add_else",
  },
  "foreach": {
    "foreach": "foreach.foreach",
  },
  "argumentSelector": {
    "unselected": "argumentSelector.unselected",
  },
  "triggerSelector": {
    "unselected": "triggerSelector.unselected",
    "timed": "triggerSelector.timed",
    "form_submit": "triggerSelector.form_submit",
    "once": "triggerSelector.once",
    "daily": "triggerSelector.daily",
    "weekly": "triggerSelector.weekly",
    "monday": "triggerSelector.monday",
    "tuesday": "triggerSelector.tuesday",
    "wednesday": "triggerSelector.wednesday",
    "thursday": "triggerSelector.thursday",
    "friday": "triggerSelector.friday",
    "saturday": "triggerSelector.saturday",
    "sunday": "triggerSelector.sunday",
  },
  "sendWebhookAction": {
    "url": "sendWebhookAction.url",
    "message": "sendWebhookAction.message",
  },
  "stringBuilder": {
    "static": "stringBuilder.static",
    "variable": "stringBuilder.variable",
    "line_break": "stringBuilder.line_break",
    "each": "stringBuilder.each",
    "if": "stringBuilder.if",
    "insert_head": "stringBuilder.insert_head",
    "insert_medium": "stringBuilder.insert_medium",
    "then": "stringBuilder.then",
    "else": "stringBuilder.else",
  },
  "action": {
    "delete_this": "action.delete_this",
    "add_head": "action.add_head",
    "add_medium": "action.add_medium",
    "null": "action.null",
    "if": "action.if",
    "foreach": "action.foreach",
    "send_webhook": "action.send_webhook",
    "get_schedule": "action.get_schedule",
  },
  "getSchedulesAction": {
    "calendar": "getSchedulesAction.calendar",
    "dateOffset": "getSchedulesAction.dateOffset",
    "scheduleArgumentName": (calendar_name: string) => `getSchedulesAction.scheduleArgumentName("${calendar_name}")`,
    "scheduleArgumentName_reverse": (name: string) => name.match(/^getSchedulesAction\.scheduleArgumentName\("(.+)"\)$/)?.[1],
    "scheduleLengthArgumentName": (calendar_name: string) => `getSchedulesAction.scheduleLengthArgumentName("${calendar_name}")`,
  },
  "variableSelector": {
    "unknown_variable": "variableSelector.unknown_variable",
    "each": {
      "scheduleName": (calendar_name: string) => `variableSelector.each.scheduleName("${calendar_name}")`,
      "scheduleTime": (calendar_name: string) => `variableSelector.each.scheduleTime("${calendar_name}")`,
      "isAllDay": (calendar_name: string) => `variableSelector.each.isAllDay("${calendar_name}")`,
      "color": (calendar_name: string) => `variableSelector.each.color("${calendar_name}")`,
    }
  },
  "color": {
    "lavender": "color.lavender",
    "sage": "color.sage",
    "grape": "color.grape",
    "flamingo": "color.flamingo",
    "banana": "color.banana",
    "tangerine": "color.tangerine",
    "peacock": "color.peacock",
    "graphite": "color.graphite",
    "blueberry": "color.blueberry",
    "basil": "color.basil",
    "tomato": "color.tomato",
  },
  "projectSelector": {
    "project_name": "projectSelector.project_name",
    "is_active": "projectSelector.is_active",
    "open": "projectSelector.open",
    "change_name_prompt": "projectSelector.change_name_prompt",
    "create_new": "projectSelector.create_new",
  },
  "topbar": {
    "save_and_quit": "topbar.save_and_quit",
    "save": "topbar.save",
    "synced": "topbar.synced",
    "unsynced": "topbar.unsynced",
  },
  "defaultVariable": {
    "nowTime": "defaultVariable.nowTime",
  },
  "formAnswer": (name: string) => `formAnswer("${name}")`,
}