export default {
  "conditionSelector": {
    "and": "All of the followings are true",
    "or": "At least one of the followings is true",
    "not": "The following is false",
    "true": "True",
    "false": "False",
    "add_front": "+",
    "add_medium": "+",
    "delete_this": "Delete this condition",
    "constant": "Constant",
    "variable": "Variable",
    "compare": "Compare",
  },
  "if": {
    "if": "If",
    "then": "Then",
    "else": "Else",
    "add_else": "+ Add Else",
  },
  "foreach": {
    "foreach": "For each",
  },
  "argumentSelector": {
    "unselected": "select......",
  },
  "triggerSelector": {
    "unselected": "select......",
    "timed": "Timed",
    "form_submit": "Form submit",
    "once": "Once",
    "daily": "Daily",
    "weekly": "Weekly",
    "monday": "Monday",
    "tuesday": "Tuesday",
    "wednesday": "Wednesday",
    "thursday": "Thursday",
    "friday": "Friday",
    "saturday": "Saturday",
    "sunday": "Sunday",
  },
  "sendWebhookAction": {
    "url": "URL",
    "message": "Message",
  },
  "stringBuilder": {
    "static": "Static text",
    "variable": "Variable",
    "line_break": "Line break",
    "each": "For each",
    "if": "If",
    "insert_head": "+ Insert",
    "insert_medium": "+ Insert",
    "then": "Then",
    "else": "Else",
  },
  "action": {
    "delete_this": "Delete this action",
    "add_head": "+ Add",
    "add_medium": "+ Add",
    "null": "select......",
    "if": "Condition branching",
    "foreach": "Repeat for each",
    "send_webhook": "Send webhook",
    "get_schedule": "Get schedule",
  },
  "getSchedulesAction": {
    "calendar": "Calendar",
    "dateOffset": "The offset from today (days)",
    "scheduleArgumentName": (calendar_name: string) => `Schedules from ${calendar_name}`,
    "scheduleArgumentName_reverse": (name: string) => name.match(/^Schedules from (.+)$/)?.[1],
    "scheduleLengthArgumentName": (calendar_name: string) => `The number of schedules from ${calendar_name}`,
  },
  "variableSelector": {
    "unknown_variable": "Unknown variable",
    "each": {
      "scheduleName": (calendar_name: string) => `Schedule name from ${calendar_name}`,
      "scheduleTime": (calendar_name: string) => `Schedule time from ${calendar_name}`,
      "isAllDay": (calendar_name: string) => `Is all day? from ${calendar_name}`,
      "color": (calendar_name: string) => `Schedule color from ${calendar_name}`,
    }
  },
  "color": {
    "lavender": "Lavender",
    "sage": "sage",
    "grape": "grape",
    "flamingo": "flamingo",
    "banana": "banana",
    "tangerine": "tangerine",
    "peacock": "peacock",
    "graphite": "graphite",
    "blueberry": "blueberry",
    "basil": "basil",
    "tomato": "tomato",
  },
  "projectSelector": {
    "project_name": "Project name",
    "is_active": "Is active",
    "open": "Open",
    "change_name_prompt": "Enter the new project name",
    "create_new": "Create new project"
  },
  "topbar": {
    "save_and_quit": "Save and quit",
    "save": "Save",
    "synced": "Synced",
    "unsynced": "Unsynced",
  },
  "defaultVariable": {
    "nowTime": "Current time",
  },
  "formAnswer": (name: string) => `Form answer: ${name}`,
}