export default {
  "conditionSelector": {
    "and": "以下のすべてが真",
    "or": "以下のいずれかが真",
    "not": "以下のいずれも真ではない",
    "true": "真",
    "false": "偽",
    "add_front": "+",
    "add_medium": "+",
    "delete_this": "この条件を削除",
    "constant": "定数",
    "variable": "変数",
    "compare": "比較",
  },
  "if": {
    "if": "もし",
    "then": "そうであれば",
    "else": "そうでなければ",
    "add_else": "+ そうでなければ",
  },
  "foreach": {
    "foreach": "それぞれについて",
  },
  "argumentSelector": {
    "unselected": "選択してください......",
  },
  "triggerSelector": {
    "unselected": "選択してください......",
    "timed": "時間トリガー",
    "form_submit": "フォーム送信トリガー",
    "once": "一度のみ",
    "daily": "毎日",
    "weekly": "毎週",
    "monday": "月曜日",
    "tuesday": "火曜日",
    "wednesday": "水曜日",
    "thursday": "木曜日",
    "friday": "金曜日",
    "saturday": "土曜日",
    "sunday": "日曜日",
  },
  "sendWebhookAction": {
    "url": "URL",
    "message": "メッセージ",
  },
  "stringBuilder": {
    "static": "テキスト",
    "variable": "変数",
    "line_break": "改行",
    "each": "それぞれについて",
    "if": "もし",
    "insert_head": "+ 挿入",
    "insert_medium": "+ 挿入",
    "then": "そうであれば",
    "else": "そうでなければ",
  },
  "action": {
    "delete_this": "このアクションを削除",
    "add_head": "+ 追加",
    "add_medium": "+ 追加",
    "null": "選択してください......",
    "if": "条件分岐",
    "foreach": "それぞれについて繰り返し",
    "send_webhook": "Webhookを送信",
    "get_schedule": "予定を取得",
  },
  "getSchedulesAction": {
    "calendar": "カレンダー",
    "dateOffset": "何日後を取得するか",
    "scheduleArgumentName": (calendar_name: string) => `${calendar_name}の予定`,
    "scheduleArgumentName_reverse": (name: string) => name.match(/^(.+)の予定$/)?.[1],
    "scheduleLengthArgumentName": (calendar_name: string) => `${calendar_name}の予定の数`,
  },
  "variableSelector": {
    "unknown_variable": "不明な変数",
    "each": {
      "scheduleName": (calendar_name: string) => `${calendar_name}の予定の名前`,
      "scheduleTime": (calendar_name: string) => `${calendar_name}の予定の時間`,
      "isAllDay": (calendar_name: string) => `${calendar_name}の予定が終日かどうか`,
      "color": (calendar_name: string) => `${calendar_name}の予定の色`,
    }
  },
  "color": {
    "lavender": "ラベンダー",
    "sage": "セージ",
    "grape": "グレープ",
    "flamingo": "フラミンゴ",
    "banana": "バナナ",
    "tangerine": "ミカン",
    "peacock": "ピーコック",
    "graphite": "グラファイト",
    "blueberry": "ブルーベリー",
    "basil": "バジル",
    "tomato": "トマト",
  },
  "projectSelector": {
    "project_name": "プロジェクト名",
    "is_active": "有効",
    "open": "開く",
    "change_name_prompt": "新しいプロジェクト名を入力してください",
    "create_new": "新しいプロジェクトを作成"
  },
  "topbar": {
    "save_and_quit": "保存して終了",
    "save": "保存",
    "synced": "同期済み",
    "unsynced": "未同期",
  },
  "defaultVariable": {
    "nowTime": "現在の時刻",
  },
  "formAnswer": (name: string) => `フォームの回答: ${name}`,
  "filter": "フィルタ",
}